name: SimpleMotd
main: dohyeon0608\simplemotd\DohyeonMotd
author: dohyeon0608
version: "1.0"
api:
  - 3.0.0

permissions:
  dohyeonmotd:
    description: motd
    default: op
    children:
      dohyeonmotd.getmotd:
        description: get motd
        default: op
      dohyeonmotd.setmotd:
        description: set motd
        default: op